In [4]:
import torch
import numpy as np
import torch.nn.functional as F
import torch.nn as nn

In [10]:
tensor_1=np.array([[1,2,3]])

In [11]:
tensor_1=torch.from_numpy(tensor_1)

In [12]:
tensor_1

tensor([[1, 2, 3]])

In [25]:
tensor_t1=torch.tensor([[1,2,3,5,6,7]])

In [26]:
tensor_t1

tensor([[1, 2, 3, 5, 6, 7]])

In [47]:
model=nn.Sequential(
    nn.Linear (6, 3),
    nn.Softmax(dim=-1)
)

In [48]:
tensor_results_t1=model(tensor_t1.float())
tensor_results_t1

tensor([[9.4768e-04, 8.9509e-05, 9.9896e-01]], grad_fn=<SoftmaxBackward0>)

In [61]:
#three classes num_class=3
#correct class is 2 (0,1, !!!!2!!!!)
tensor_target1=torch.tensor([[0,0,1]])
one_hot_enc=F.one_hot(torch.tensor([2]), num_classes=3)
one_hot_enc

tensor([[0, 0, 1]])

In [62]:
one_hot_enc1=F.one_hot(torch.tensor(1), num_classes=3)
one_hot_enc1

tensor([0, 1, 0])

In [68]:
one_hot_enc_all=F.one_hot(torch.arange(0,3), num_classes=3)
one_hot_enc_all

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [63]:
loss_f1=nn.CrossEntropyLoss()
tensor_results_t1.shape
output1=loss_f1(tensor_results_t1.double(), one_hot_enc.double())

In [64]:
one_hot_enc.shape

torch.Size([1, 3])