In [32]:
import torch


In [35]:
list_a=[1,2,3,4,5]

In [36]:
#check list_a data type
list_b=[1,2,3, 4]
#check data type for list
type(list_a)
type(list_b)

list

In [37]:
tensor_a=torch.tensor(list_a+list_b)


In [38]:
tensor_a

tensor([1, 2, 3, 4, 5, 1, 2, 3, 4])

In [39]:
tensor_a.dtype

torch.int64

In [40]:
tensor_b=torch.stack((tensor_a, tensor_a), dim=0)

In [42]:
tensor_b

tensor([[1, 2, 3, 4, 5, 1, 2, 3, 4],
        [1, 2, 3, 4, 5, 1, 2, 3, 4]])

In [45]:
tensor_c=torch.stack((tensor_a, tensor_a), dim=1)

In [46]:
tensor_c.shape

torch.Size([9, 2])

In [47]:
tensor_b.shape

torch.Size([2, 9])

In [48]:
print(tensor_c)

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])


In [49]:
print(tensor_b)

tensor([[1, 2, 3, 4, 5, 1, 2, 3, 4],
        [1, 2, 3, 4, 5, 1, 2, 3, 4]])


In [51]:
import numpy as np
array_a=np.array([1,2,3,4,5])
print(array_a)

[1 2 3 4 5]


In [53]:
tensor_a=torch.from_numpy(array_a)
(array_a)

array([1, 2, 3, 4, 5])

In [54]:
import torch.nn as nn

In [71]:
input_tensor1=torch.tensor([[1.0,2.0,3.0]])
input_tensor0=torch.tensor([1.0,2.0,3.0])
input_tensor2=torch.tensor([[[1.0,2.0,3.0]]])

In [72]:
print(input_tensor0.shape,
input_tensor1.shape,
input_tensor2.shape)

torch.Size([3]) torch.Size([1, 3]) torch.Size([1, 1, 3])


In [73]:
print(input_tensor2)

tensor([[[1., 2., 3.]]])


In [80]:
linear_layer=nn.Linear(3,2)

In [81]:
output=linear_layer(input_tensor2)

In [82]:
output

tensor([[[-1.4046,  1.2170]]], grad_fn=<ViewBackward0>)

In [83]:
linear_layer.weight

Parameter containing:
tensor([[-0.3931,  0.2684, -0.5399],
        [ 0.4109,  0.4819,  0.0666]], requires_grad=True)

In [84]:
linear_layer.bias

Parameter containing:
tensor([ 0.0713, -0.3574], requires_grad=True)

In [87]:
model=nn.Sequential(
    nn.Linear(3,2),
    nn.Linear(5,1),
    nn.Linear(1,1)
)

In [88]:
model

Sequential(
  (0): Linear(in_features=3, out_features=2, bias=True)
  (1): Linear(in_features=5, out_features=1, bias=True)
  (2): Linear(in_features=1, out_features=1, bias=True)
)

In [89]:
score=torch.tensor([[0.8]])

In [90]:
sigmoid=nn.Sigmoid()

In [91]:
probability=sigmoid(score)

In [92]:
print(probability)

tensor([[0.6900]])


In [93]:
probability.item()

0.6899744868278503

In [94]:
scores=torch.tensor([[1.0, 1.2, 1.4, 1.5, 1.6, 1.7]])
softmax=nn.Softmax( dim=1 )

In [95]:
probability=softmax(scores)

In [96]:
print(probability)

tensor([[0.1087, 0.1328, 0.1622, 0.1793, 0.1981, 0.2189]])
